# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: iedesigner blog
email: peter@iedesigner.com
description: i.e. all things interactive
url: "https://iedesigner.github.io" # the base hostname & protocol for your site
twitter_username: ie_designer

# Build settings
markdown: kramdown
permalink: /:title
